// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['bridge']['ConnectionService']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['bridge']['ConnectionService']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['bridge']['ConnectionService']['Disconnect']();
}

export function GetConfig() {
  return window['go']['bridge']['ConnectionService']['GetConfig']();
}

export function GetProfiles() {
  return window['go']['bridge']['ConnectionService']['GetProfiles']();
}

export function SaveConfig(arg1) {
  return window['go']['bridge']['ConnectionService']['SaveConfig'](arg1);
}

export function State() {
  return window['go']['bridge']['ConnectionService']['State']();
}

export function SwitchProfile(arg1) {
  return window['go']['bridge']['ConnectionService']['SwitchProfile'](arg1);
}

export function TestConnect(arg1) {
  return window['go']['bridge']['ConnectionService']['TestConnect'](arg1);
}
