// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function Connect(arg1:bridge.ConnectionConfig):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<bridge.ConnectionConfig>;

export function GetProfiles():Promise<Array<bridge.ProfileSummary>>;

export function SaveConfig(arg1:bridge.ConnectionConfig):Promise<void>;

export function State():Promise<string>;

export function SwitchProfile(arg1:string):Promise<bridge.ConnectionConfig>;

export function TestConnect(arg1:bridge.ConnectionConfig):Promise<bridge.TestResult>;
