// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConsole() {
  return window['go']['bridge']['ConsoleService']['ClearConsole']();
}

export function ExportConsole(arg1, arg2) {
  return window['go']['bridge']['ConsoleService']['ExportConsole'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['bridge']['ConsoleService']['SetContext'](arg1);
}
