// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {engine} from '../models';

export function ClearConsole():Promise<void>;

export function ExportConsole(arg1:string,arg2:Array<string>):Promise<bridge.ExportResult>;

export function GetParamSpecs(arg1:string):Promise<Array<engine.ParamSpec>>;

export function GetResponseCodes(arg1:string):Promise<Array<engine.ResponseCode>>;
