// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPacks() {
  return window['go']['bridge']['ExtService']['ListPacks']();
}

export function ReloadPacks() {
  return window['go']['bridge']['ExtService']['ReloadPacks']();
}
