// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePack(arg1) {
  return window['go']['bridge']['ExtService']['DeletePack'](arg1);
}

export function ImportPack(arg1) {
  return window['go']['bridge']['ExtService']['ImportPack'](arg1);
}

export function ListPacks() {
  return window['go']['bridge']['ExtService']['ListPacks']();
}

export function PickPackFile() {
  return window['go']['bridge']['ExtService']['PickPackFile']();
}

export function ReloadPacks() {
  return window['go']['bridge']['ExtService']['ReloadPacks']();
}

export function SetContext(arg1) {
  return window['go']['bridge']['ExtService']['SetContext'](arg1);
}
