// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {context} from '../models';

export function DeletePack(arg1:string):Promise<void>;

export function GetPackJSON(arg1:string):Promise<string>;

export function ImportPack(arg1:string):Promise<bridge.PackInfo>;

export function ImportPackJSON(arg1:string):Promise<bridge.PackInfo>;

export function ListPacks():Promise<Array<bridge.PackInfo>>;

export function PickPackFile():Promise<string>;

export function ReloadPacks():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPackEnabled(arg1:string,arg2:boolean):Promise<void>;
