// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function ListPacks():Promise<Array<bridge.PackInfo>>;

export function ReloadPacks():Promise<void>;
