// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoReportState() {
  return window['go']['bridge']['MessageService']['AutoReportState']();
}

export function DefaultGroups(arg1) {
  return window['go']['bridge']['MessageService']['DefaultGroups'](arg1);
}

export function EnsureAutoReport() {
  return window['go']['bridge']['MessageService']['EnsureAutoReport']();
}

export function GetGroups() {
  return window['go']['bridge']['MessageService']['GetGroups']();
}

export function GetSchema(arg1) {
  return window['go']['bridge']['MessageService']['GetSchema'](arg1);
}

export function Preview() {
  return window['go']['bridge']['MessageService']['Preview']();
}

export function RespondAck(arg1, arg2) {
  return window['go']['bridge']['MessageService']['RespondAck'](arg1, arg2);
}

export function RespondRemoteSecondLayer(arg1, arg2) {
  return window['go']['bridge']['MessageService']['RespondRemoteSecondLayer'](arg1, arg2);
}

export function RespondParamQuery(arg1, arg2) {
  return window['go']['bridge']['MessageService']['RespondParamQuery'](arg1, arg2);
}

export function SaveGroups(arg1) {
  return window['go']['bridge']['MessageService']['SaveGroups'](arg1);
}

export function SendExtension(arg1) {
  return window['go']['bridge']['MessageService']['SendExtension'](arg1);
}

export function SendRealtime() {
  return window['go']['bridge']['MessageService']['SendRealtime']();
}

export function SendReissue(arg1, arg2, arg3) {
  return window['go']['bridge']['MessageService']['SendReissue'](arg1, arg2, arg3);
}

export function SetAutoReport(arg1, arg2) {
  return window['go']['bridge']['MessageService']['SetAutoReport'](arg1, arg2);
}

export function SetExtAutoReport(arg1, arg2, arg3) {
  return window['go']['bridge']['MessageService']['SetExtAutoReport'](arg1, arg2, arg3);
}

export function SetTrackReplay(arg1) {
  return window['go']['bridge']['MessageService']['SetTrackReplay'](arg1);
}
