// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';
import {bridge} from '../models';
import {engine} from '../models';

export function DefaultGroups(arg1:string):Promise<schema.GroupsPayload>;

export function GetGroups():Promise<schema.GroupsPayload>;

export function GetSchema(arg1:string):Promise<Array<schema.GroupSchema>>;

export function Preview():Promise<bridge.PreviewResult>;

export function RespondAck(arg1:number,arg2:number):Promise<void>;

export function RespondRemoteSecondLayer(arg1:string,arg2:string):Promise<void>;

export function RespondParamQuery(arg1:Array<engine.ParamResponseRow>,arg2:number):Promise<void>;

export function SaveGroups(arg1:schema.GroupsPayload):Promise<void>;

export function SendRealtime():Promise<void>;

export function SendReissue(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetAutoReport(arg1:boolean,arg2:number):Promise<void>;
