// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParsePacket(arg1, arg2) {
  return window['go']['bridge']['ParserService']['ParsePacket'](arg1, arg2);
}

export function ParserPacks() {
  return window['go']['bridge']['ParserService']['ParserPacks']();
}
