// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';
import {bridge} from '../models';

export function ParsePacket(arg1:string,arg2:string):Promise<parser.Result>;

export function ParserPacks():Promise<Array<bridge.PackInfo>>;
