// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLog() {
  return window['go']['bridge']['ServerService']['ClearLog']();
}

export function ExportLog() {
  return window['go']['bridge']['ServerService']['ExportLog']();
}

export function LoadConfig() {
  return window['go']['bridge']['ServerService']['LoadConfig']();
}

export function SendExtCommand(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['ServerService']['SendExtCommand'](arg1, arg2, arg3, arg4);
}

export function ServerExtCommands() {
  return window['go']['bridge']['ServerService']['ServerExtCommands']();
}

export function Sessions() {
  return window['go']['bridge']['ServerService']['Sessions']();
}

export function Start(arg1, arg2) {
  return window['go']['bridge']['ServerService']['Start'](arg1, arg2);
}

export function Status() {
  return window['go']['bridge']['ServerService']['Status']();
}

export function Stop() {
  return window['go']['bridge']['ServerService']['Stop']();
}

export function UpdateIdle(arg1, arg2) {
  return window['go']['bridge']['ServerService']['UpdateIdle'](arg1, arg2);
}
