// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {servermode} from '../models';

export function ClearLog():Promise<void>;

export function ExportLog():Promise<string>;

export function LoadConfig():Promise<bridge.ServerConfig>;

export function SendExtCommand(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function ServerExtCommands():Promise<Array<bridge.ExtCommandInfo>>;

export function Sessions():Promise<Array<servermode.Session>>;

export function Start(arg1:bridge.ServerConfig,arg2:boolean):Promise<servermode.Status>;

export function Status():Promise<servermode.Status>;

export function Stop():Promise<void>;

export function UpdateIdle(arg1:boolean,arg2:number):Promise<void>;
