// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function GetAppSettings():Promise<bridge.AppSettings>;

export function SetAppSettings(arg1:bridge.AppSettings):Promise<void>;
