// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppSettings() {
  return window['go']['bridge']['SettingsService']['GetAppSettings']();
}

export function SetAppSettings(arg1) {
  return window['go']['bridge']['SettingsService']['SetAppSettings'](arg1);
}
