// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory(arg1:string):Promise<void>;

export function StoragePaths():Promise<Record<string, string>>;
