// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory(arg1) {
  return window['go']['bridge']['SystemService']['OpenDirectory'](arg1);
}

export function StoragePaths() {
  return window['go']['bridge']['SystemService']['StoragePaths']();
}
