// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceForReport() {
  return window['go']['bridge']['TrackService']['AdvanceForReport']();
}

export function ClearTrack() {
  return window['go']['bridge']['TrackService']['ClearTrack']();
}

export function FailOnSend(arg1) {
  return window['go']['bridge']['TrackService']['FailOnSend'](arg1);
}

export function ImportTrack(arg1) {
  return window['go']['bridge']['TrackService']['ImportTrack'](arg1);
}

export function PickTrackFile() {
  return window['go']['bridge']['TrackService']['PickTrackFile']();
}

export function ReplayStatus() {
  return window['go']['bridge']['TrackService']['ReplayStatus']();
}

export function SetContext(arg1) {
  return window['go']['bridge']['TrackService']['SetContext'](arg1);
}

export function StartReplay(arg1) {
  return window['go']['bridge']['TrackService']['StartReplay'](arg1);
}

export function StopReplay() {
  return window['go']['bridge']['TrackService']['StopReplay']();
}
