// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {context} from '../models';

export function AdvanceForReport():Promise<void>;

export function ClearTrack():Promise<void>;

export function FailOnSend(arg1:Error):Promise<void>;

export function ImportTrack(arg1:string):Promise<bridge.TrackInfo>;

export function PickTrackFile():Promise<string>;

export function ReplayStatus():Promise<bridge.TrackReplayStatus>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartReplay(arg1:boolean):Promise<void>;

export function StopReplay():Promise<void>;
