// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyUpdate():Promise<void>;

export function CancelDownload():Promise<void>;

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function ConsumeLastResult():Promise<updater.ApplyOutcome>;

export function CurrentVersion():Promise<string>;

export function DownloadUpdate():Promise<updater.DownloadResult>;
