// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['bridge']['UpdaterService']['ApplyUpdate']();
}

export function CancelDownload() {
  return window['go']['bridge']['UpdaterService']['CancelDownload']();
}

export function CheckUpdate() {
  return window['go']['bridge']['UpdaterService']['CheckUpdate']();
}

export function ConsumeLastResult() {
  return window['go']['bridge']['UpdaterService']['ConsumeLastResult']();
}

export function CurrentVersion() {
  return window['go']['bridge']['UpdaterService']['CurrentVersion']();
}

export function DownloadUpdate() {
  return window['go']['bridge']['UpdaterService']['DownloadUpdate']();
}
