// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['bridge']['UpdaterService']['CheckUpdate']();
}

export function CurrentVersion() {
  return window['go']['bridge']['UpdaterService']['CurrentVersion']();
}
