// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function CurrentVersion():Promise<string>;
